### ISSUE TITLE
Regarding Data

### ISSUE THREAD

**Issue by kuber382583** [raquelsilva/Seismic-well-tie#2]
Hii, 
 Can you please provide us the data you work on, asap. The uploaded data are different.
Thankyou

**Comment by raquelsilva** [comment]
Hello! Sorry for my late reply. 

I cannot provide the data, sorry. You can also find information about seismic-well tie in the PyTie project. This one here is older, was my first try. 

In regards to data, it's possible that you will need to edit the code to adapt to your data. If you need the source code go to Pypi.org, PyTie.

Kind regards,
Raquel
